name: Update MonsterSpy cache

on:
  schedule:
    - cron: '* */12 * * *' # every 5 minutes for testing
  workflow_dispatch:

jobs:
  update-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd monitor
          npm ci

      - name: Run monitor
        run: |
          cd monitor
          node monitor.js

      - name: Commit cache.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add monitor/cache.json public/cache.json
          git commit -m "Update MonsterSpy cache" || echo "No changes to commit"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} HEAD:main


